### PR TITLE
GDHI-fix: update country profile year selector to handle selected year

### LINKED ISSUE #8: Add year selector to the map view
Currently, the map always displays data for the default year set in the backend, with no way for users to change it. Add a year selector to the landing map page (similar to the one on the country profile page) that allows users to switch between available years and see the map update accordingly.

Expected Behavior: 
- A year selector is visible on the map page
- Selecting a year re-fetches and re-renders the map with data for that year
- The selector defaults to the latest available year
- The selected year persists when interacting with the map (clicking countries, filters etc.)

### PR DESCRIPTION
**Pull request by fred-maina**

### CODE REVIEW

File: src/components/countryProfile/country-profile-year-selector.vue [hunk 1]
```diff
@@ -24,21 +23,19 @@ export default Vue.extend({
...
-        });
-      });
-    },
     fetchPublishedYearsForACountry(countryCode) {
       axios
         .get(`/api/countries/${countryCode}/published_years`)
         .then((response) => {
           this.years = response.data;
+          if (this.years.length && this.selectedYear === null) {
+            this.selectedYear = this.years[0];
```
Comment (arsemagebremichael) [inline src/components/countryProfile/country-profile-year-selector.vue]: this.years[0] on line where selectedYear is set... what happens if years comes back empty? Should have a guard there.

**Review by arsemagebremichael — COMMENTED** [review]
Hey @fred-maina, Looks good and wanted to ask for a small thing, if the API returns an empty array, this.years[0] will be undefined and selectedYear will be set to undefined. Worth adding a guard like this.years.length ? this.years[0] : null just to be safe.

**Review by arsemagebremichael — APPROVED** [review]
